### ISSUE TITLE
is it possible to access synology using this wrapper from public/making request from browser?

### ISSUE THREAD

**Issue by fazriachyar** [N4S4/synology-api#152]
I'm attempting to integrate this Synology wrapper into a web application to access my Synology device directly from the browser. I'd like to confirm if this wrapper is designed for client-side usage. Are there any specific configuration steps needed to make this work within a browser environment?

**Comment by N4S4** [comment]
Hello, 

Yes I can confirm this is a client side wrapper. I am sure that with some work you will be able to use it in the browser. No specific steps other than what is written in the readme file. Bear on mind that some functions might not work as expected. May I ask what is making you use this wrapper for browser use instead of the built in synology DSM?

**Comment by fazriachyar** [comment]
> Hello,
> 
> Yes I can confirm this is a client side wrapper. I am sure that with some work you will be able to use it in the browser. No specific steps other than what is written in the readme file. Bear on mind that some functions might not work as expected. May I ask what is making you use this wrapper for browser use instead of the built in synology DSM?
