### ISSUE TITLE
Logging with custom base_url instead of ip/port and use SSL/HTTPS

### ISSUE THREAD

**Issue by tduboys** [N4S4/synology-api#20]
On the auth.py, you creates the base_url using the params ip_address/port.
It should be great if we can directly give a base_url for some reasons : 
- some times, the NAS is behind a reverse proxy and the base URL contains a subdirectory
- ~~you can choose behind http/https~~ added with pr #42 
- only one simple param to use

I will try to submit a PR that can manage both ways, to not break something.

**Comment by tduboys** [comment]
Hi,
I looked on the Improving-code branch.
I liked the simplicity of the master branch, but now, It looks too complicated for me. I tried to understand the good way to work with this new code, and I didnt succed to login on my NAS…

As I see, this branch is a work-in-progress. I will wait for a merge on master to try again.

**Comment by N4S4** [comment]
yes is still in progress and most things won't work, probably also the login function, we didn't work much on it as we don't have much time due to our jobs,
anyway ithe plan of improving-code branch  is to have a better way to use all modules (filestation, downloadstation etc.) with one SID without logging in again reducing the process workload of the sinology and of the user, also to simplify the processi of modifying functions thanks to the decorator in synology.py module.
I dunno if the above explanation is clear let me know please!

**Comment by fletchgraham** [comment]
would this allow for using the webapi with quickconnect?

**Comment by N4S4** [comment]
@fletchgraham it should work, make sure you have port forwarding set up properly  
let's keep this section tidy for the issues only,
please if you have any other question I have just made a group where we can talk on Telegram you can find it at https://t.me/SynologyApi or on Slack at https://bit.ly/SynologyApi
both are newely made so no one except me is in them for now

**Comment by N4S4** [comment]
Https option has been added from @Egor pr #22 with little modification.
