### ISSUE TITLE
Possible api change

### ISSUE THREAD

**Issue by nitko12** [N4S4/synology-api#74]
Hi,

I'm using your module in a project, and after update to DSM 7 it throws and error on login

<img width="702" alt="Screenshot 2021-09-22 at 08 15 14" src="https://user-images.githubusercontent.com/34972330/134295297-bd910cd0-879c-4bd2-993f-ea005f329ce8.png">

Am I doing something wrong? 

On closer inspection it seems the drive returns code 103 somewhere in authentification process.

**Comment by N4S4** [comment]
Hi,

Could you post the entire authentication code?

**Comment by nitko12** [comment]
Whole of it is in the picture

```
from synology_api import filestation, downloadstation
fl = filestation("192.168.5.100", "5000", "<user>", "<password>")
```

Second line produces the error somewhere in the module, if I'm not mistaking, here:
https://github.com/N4S4/synology-api/blob/3893dde89679a181c479c744bdea19da809cb594/synology_api/auth.py#L37

**Comment by tjsry0466** [comment]
change dsm_version 2 -> '3'

**Comment by N4S4** [comment]
Since the last version you need to specify dsm version otherwise DSM 6 will be as default, in the readme file there are instructions, 

fl = filestation.FileStation('Synology Ip', 'Synology Port', 'Username', 'Password', secure=True, cert_verify=True, dsm_version=7)


Try like this and let me know please

**Comment by N4S4** [comment]
Issue close due to inactivity
